version: 2
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: bitagent
    goos:
      - linux
      # - windows
      # - darwin
      # - freebsd
    goarch:
      - amd64
      # - 386
      # - arm
      # - arm64
    ldflags:
      - -s -w
      - -X main.Name={{.ProjectName}}
      - -X main.Version={{.Version}}
archives:
  - name_template: '{{ .ProjectName }}_{{- .Version }}_{{- if eq .Os "freebsd" }}FreeBSD{{- else }}{{ title .Os }}{{ end }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else if eq .Arch "arm64" }}ARM64{{- else if eq .Arch "arm" }}ARM{{- else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: checksums.txt
release:
  draft: true
