# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  validate-goreleaser:
    name: Validate .goreleaser.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set GOVERSION env
        id: set-goversion-env
        run: echo "GOVERSION=$(go version)" >> $GITHUB_OUTPUT
      - name: Validate .goreleaser.yml with goreleaser-action
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
